### ISSUE TITLE
Button Hover effects!!

### ISSUE THREAD

**Issue by raxraj** [raxraj/Colorify#1]
We Currently support a very limited number of button hover effects!!
If you can add some button hover effects ! It will be really nice!

**Comment by ghost** [comment]
i would like to contribute to this. @raxraj if its still open!

**Comment by raxraj** [comment]
@steelbeginner .. This open for contribution!! The issue isn't solved yet!! So you're welcome to contribute!!

**Comment by Raal9410** [comment]
Hey @raxraj ! I would like to contribute if I still can

:)

**Comment by raxraj** [comment]
@Raal9410 ...
The repo is open for Contribution you can work on the issue provided!! Or you may create a pull request on your own!!

**Comment by ghost** [comment]
I would like to know the naming convention you use for your css classes and some more guidelines if you may.

**Comment by raxraj** [comment]
Yes Sure!!
Every element starts with cy : Colorify

The buttons are in a different CSS file namely cybuttons !!
You can find how we have added our buttons naming conventions just visit

http://colorify.tech
